
What is PyTorch?
================
https://pytorch.org/docs/stable/index.html

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


NumPy Bridge
------------
1. Tensors are similar to NumPy’s arrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.  

2. All the Tensors on the CPU except a CharTensor support converting to
NumPy and back. Converting a Torch Tensor to a NumPy array and vice versa is a breeze.  

3. The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

In [1]:
import torch
import numpy as np 

#### GPU available

In [2]:
# Examine your GPUs are available for pytorch (False for CPU version of pytorch)
torch.cuda.is_available()

False

#### array <-> tensor

In [2]:
data = [[1, 2],[3, 4]]
# tensor to array
x_tensor = torch.tensor(data); print(x_tensor)
x_tensor2array = x_tensor.numpy(); print(x_tensor2array); print()
# array to tensor
x_array = np.array(data); print(x_array)
x_array2tenor = torch.from_numpy(x_array); print(x_array2tenor)

tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


## Define tensor

In [4]:
data = [[1, 2],[3, 4]]
x = torch.tensor(data); print(x)

tensor([[1, 2],
        [3, 4]])


In [2]:
# empty/rand/ones/zeros/eye(), xxx_like()
# the difference is you can fill dimensions without brackets at the beginning for these functions
x = torch.empty(2, 3); print(x)
x = torch.rand(2, 3); print(x) # initialization from the Gaussian distribution of N(0,1)
# cuda() means translating your tensors into GPUs
x = torch.zeros(2, 3, dtype=torch.float)#.cuda(); 
print(x) # if your device is CPU, please delete the cuda()
y = torch.rand_like(x) # _like means the same shape, data type and device(GPU or CPU)
print(y) 

tensor([[1.4586e-19, 1.1578e+27, 2.0780e-07],
        [6.0542e+22, 7.8675e+34, 4.6894e+27]])
tensor([[0.8599, 0.7811, 0.9866],
        [0.7674, 0.7119, 0.5672]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.8394, 0.7471, 0.0390],
        [0.8471, 0.0797, 0.0625]])


In [7]:
# get shape
print(x.shape)
print(x.size())

torch.Size([2, 3])
torch.Size([2, 3])


If you have a one element tensor, use ``.item()`` to get the value as a Python number

In [2]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.9617])
0.9617466330528259


#### A bunch of operations in numpy have corresponding functions in torch

In [9]:
torch.arange(10)
# torch.stack()
# torch.concatenate()
# torch.squeeze()/unsqueeze()
# torch.flatten()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# permute -> transpose in numpy, to switch the order of dimensions
x = torch.arange(24).reshape(2,3,4)
y = x.permute([2,0,1]); print(y.shape)

torch.Size([4, 2, 3])


## Computation of Tensors
Note: The default calculation is element-wise calculation (+ - * /)

In [13]:
x = torch.arange(6).reshape(2,3); print(x)
y = torch.rand(2, 3)
print(x + y)
print(x*y)
print(x/y)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0.4898, 1.0310, 2.6730],
        [3.3447, 4.7866, 5.9012]])
tensor([[0.0000, 0.0310, 1.3461],
        [1.0340, 3.1466, 4.5060]])
tensor([[ 0.0000, 32.2552,  2.9716],
        [ 8.7039,  5.0849,  5.5482]])


### Matrix Multiplication

In [14]:
# torch.mul() equals "*": Element-wise multiplication
a = torch.rand(2, 3);print(a)
b = torch.rand(2, 3);print(b)
print(torch.mul(a, b))
print(torch.mul(a, b).size())
print((a*b))
print((a*b).shape)

tensor([[0.3828, 0.1071, 0.9814],
        [0.9670, 0.0534, 0.4044]])
tensor([[0.7637, 0.0747, 0.9606],
        [0.7165, 0.2641, 0.3816]])
tensor([[0.2923, 0.0080, 0.9427],
        [0.6929, 0.0141, 0.1543]])
torch.Size([2, 3])
tensor([[0.2923, 0.0080, 0.9427],
        [0.6929, 0.0141, 0.1543]])
torch.Size([2, 3])


In [17]:
# torch.mm(): the common mathematical matrix multiplication
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)
print(torch.mm(mat1, mat2).size())
print((mat1 @ mat2).shape)

torch.Size([2, 3])
torch.Size([2, 3])


In [19]:
# torch.matmul() equals "@": Matrix product of two tensors, it includes matrix multiplication methods of different dimensions
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(10, 4, 5)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3, 5])

**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described [here](https://pytorch.org/docs/torch).

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [13]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
x = torch.arange(6).reshape(2,3) # x created in CPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    # y.cuda() is also an easy method to move onto the default GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


## Exercise1
Broadcasting is an underlying rules for dealing with unpaired tensors.  
[Broadcasting tutorial](https://deeplearninguniversity.com/pytorch/pytorch-broadcasting/)

## Exercise2
[Pytorch official website](https://pytorch.org/tutorials/) has provided sufficient tutorials for beginners.
Familiarize yourself with PyTorch concepts and modules. Learn how to load data, build deep neural networks, train and save your models in [quickstart guide](https://pytorch.org/tutorials/beginner/basics/intro.html).

We also provide old version of the pytorch tutorials in file folder "old_pytorch_tutorials". The tutorials in [Pytorch official website](https://pytorch.org/tutorials/) is more recommended.
