# Practice 2 - Numpy
Students are required to complete the code implementation for Problems 1-7, and to conduct exploratory analysis for Problems 8 and 9, providing well-reasoned answers to the corresponding questions.

                                                                                                      
### DDL: Oct.12
* The practice will be checked in this lab class or the next lab class before the DDL by teachers or SAs.

#### What will be tested: 
* That you understand every line of your code, not just copy from somewhere 
* That your program compiles correctly
* Correctness of the program logic 
* That the result is obtained in a reasonable time 

#### Grading: 
* Submissions on time: 60-100 points.
* Late submissions  : 0 points. 

**Q1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.**

In [1]:
#1
import numpy as np

q1 = np.zeros((10, 10))
q1[1:-1, 1:-1] = 1
print(q1)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**Q2. Create a 5*5 matrix with each row being 0 to 4.**

In [2]:
#2
q2 = np.zeros((5, 5)) + np.arange(5)
print(q2)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


**Q3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]]).**

In [3]:
#3
arr = np.zeros((8, 8))
arr[::2, 1::2] = 1 
arr[1::2, ::2] = 1 
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**Q4. output all the odd numbers in the array [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].**
     
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [4]:
#4
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
q4 = arr[arr % 2 == 1]
print(q4)

[1 3 5 7 9]


**Q5. Apply Z-score normalization to a 5×5 random matrix.**

In [5]:
#5
arr = np.random.random((5, 5))
mean = arr.mean()
std = arr.std()
q5 = (arr - mean) / std
print(q5)

[[-1.27545046  0.59125782 -0.41677899  0.14236495  1.65179802]
 [-1.70679289 -1.12362882  1.25057023  0.14637931  1.44869546]
 [ 0.27318336  0.01387406  0.71941763  0.58778267  1.15000152]
 [-1.4894448   0.25745124 -1.17122471 -0.42997201 -0.6775507 ]
 [ 1.79319032 -1.22868524 -0.05937946  0.42915753 -0.87621602]]


**Q6.Generate a random 10×2 matrix representing Cartesian coordinates, and transform the coordinates into their polar form.**

In [6]:
#6
arr = np.random.random((10, 2))
x = arr[:, 0]
y = arr[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
q6 = np.column_stack((r, theta))
print(q6)

[[0.71424672 0.35030073]
 [0.64431453 1.01038692]
 [0.92291823 0.56339849]
 [0.73186601 1.45031595]
 [0.7167138  0.09069992]
 [0.99022566 0.83690108]
 [1.08915268 0.63854005]
 [0.91492539 0.58800261]
 [0.41787576 1.50064181]
 [0.7594054  1.37708766]]


**Q7.Given the vector [1, 2, 3, 4, 5], construct a new vector by inserting three consecutive zeros between each element.**

In [7]:
#7
arr = np.array([1, 2, 3, 4, 5])
q7 = np.zeros(len(arr) + (len(arr) - 1) * 3, dtype=arr.dtype)
q7[::4] = arr
print(q7)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


**Q8. What are the result of the following expressions?First guess a result, then print the result, and finally find why.**

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 
hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2))


In [8]:
#8
print("0 * np.nan:", 0 * np.nan)
print("np.nan == np.nan:", np.nan == np.nan)
print("np.inf > np.nan:", np.inf > np.nan)
print("np.nan - np.nan:", np.nan - np.nan)
print("np.nan in set([np.nan]):", np.nan in set([np.nan]))
print("0.3 == 3 * 0.1:", 0.3 == 3 * 0.1)

0 * np.nan: nan
np.nan == np.nan: False
np.inf > np.nan: False
np.nan - np.nan: nan
np.nan in set([np.nan]): True
0.3 == 3 * 0.1: False


**Q9. What are the result of the following expressions?First guess a result, then print the result, and finally find why.**
(Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)




In [9]:
#9
print("np.array(0) / np.array(0):", np.array(0) / np.array(0))
print("np.array(0) // np.array(0):", np.array(0) // np.array(0))
print("np.array([np.nan]).astype(int).astype(float):", np.array([np.nan]).astype(int).astype(float))

np.array(0) / np.array(0): nan
np.array(0) // np.array(0): 0
np.array([np.nan]).astype(int).astype(float): [0.]


/var/folders/y_/8g0ym9617yz6ss0zzw8x8vc00000gn/T/ipykernel_54824/3834757046.py:2: RuntimeWarning: invalid value encountered in divide
  print("np.array(0) / np.array(0):", np.array(0) / np.array(0))
/var/folders/y_/8g0ym9617yz6ss0zzw8x8vc00000gn/T/ipykernel_54824/3834757046.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print("np.array(0) // np.array(0):", np.array(0) // np.array(0))
/var/folders/y_/8g0ym9617yz6ss0zzw8x8vc00000gn/T/ipykernel_54824/3834757046.py:4: RuntimeWarning: invalid value encountered in cast
  print("np.array([np.nan]).astype(int).astype(float):", np.array([np.nan]).astype(int).astype(float))
