# Array
https://numpy.org/doc/stable/reference/index.html

In [1]:
import numpy as np

## Define array

#### np.array() & data type

In [3]:
 #a = np.array([1, 2], dtype=int)
a = np.array([[1],[2]], dtype=int)
# a = np.array([[1, 2],[3, 4]], dtype=float)
# a = np.array([[1, 2],[3, 4]])
# a = np.array([[1., 2],[3, 4]])
# a = np.array([1, 2], dtype=np.int8)
# a = np.array([1, 2], dtype=np.float32)
print(a, a.dtype, a.shape)

[[1]
 [2]] int32 (2, 1)


#### np.empty/zeros/ones/eyes()

In [6]:
x = np.empty([3, 2], dtype=int) # empty array, without any control for initialization
print(x, x.shape)

[[   940      0]
 [   940      0]
 [131074      0]] (3, 2)


In [7]:
y = np.zeros([3, 2]) # zero initialization
print(y, y.shape) 

[[0. 0.]
 [0. 0.]
 [0. 0.]] (3, 2) float64


In [8]:
z = np.ones([2,3]) # one initialization
print(z, z.shape,z.dtype)

[[1. 1. 1.]
 [1. 1. 1.]] (2, 3) float64


In [5]:
t = np.eye(5) # one initialization
print(t, t.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] (5, 5)


In [12]:
a = np.array([1, 2], dtype=np.float32)
aint = np.int32(a)
print(aint,aint.dtype)

[1 2] int32


#### np.arange() & reshape

In [8]:
a = np.arange(24); print(a)
b = a.reshape(-1,6); print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


## Exercise

In [4]:
# Define an array full of one values whose shape is [3,4,5] and dtype is "float".
np.ones([3,4,5], dtype=float)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])