# Practice 2 - Numpy
Students are required to complete the code implementation for Problems 1-7, and to conduct exploratory analysis for Problems 8 and 9, providing well-reasoned answers to the corresponding questions.

                                                                                                      
### DDL: Oct.12
* The practice will be checked in this lab class or the next lab class before the DDL by teachers or SAs.

#### What will be tested: 
* That you understand every line of your code, not just copy from somewhere 
* That your program compiles correctly
* Correctness of the program logic 
* That the result is obtained in a reasonable time 

#### Grading: 
* Submissions on time: 60-100 points.
* Late submissions  : 0 points. 

**Q1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.**

In [77]:
#1
import numpy as np

q1 = np.zeros((10, 10))
q1[1:-1, 1:-1] = 1
print(q1)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**Q2. Create a 5*5 matrix with each row being 0 to 4.**

In [78]:
#2
q2 = np.zeros((5, 5)) + np.arange(5)
print(q2)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


**Q3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]]).**

In [79]:
#3
arr = np.zeros((8, 8))
arr[::2, 1::2] = 1 
arr[1::2, ::2] = 1 
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**Q4. output all the odd numbers in the array [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].**
     
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [80]:
#4
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
q4 = arr[arr % 2 == 1]
print(q4)

[1 3 5 7 9]


**Q5. Apply Z-score normalization to a 5×5 random matrix.**

In [81]:
#5
arr = np.random.random((5, 5))
mean = arr.mean()
std = arr.std()
q5 = (arr - mean) / std
print(q5)

[[ 1.10642812  0.34749147  0.64525871  1.09989482 -0.6827439 ]
 [-1.60788853  0.47702907 -2.45458891  1.11276645 -0.5901554 ]
 [-0.44483669  1.5678197  -0.44251588 -0.51145806 -0.57668853]
 [ 0.74601356  0.77004993  1.35184832  0.81059928 -1.20640184]
 [-0.26336664 -1.41921571 -0.5102447   0.21222557  0.46267979]]


**Q6.Generate a random 10×2 matrix representing Cartesian coordinates, and transform the coordinates into their polar form.**

In [82]:
#6
arr = np.random.random((10, 2))
x = arr[:, 0]
y = arr[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
q6 = np.column_stack((r, theta))
print(q6)

[[0.37404218 1.32523964]
 [1.17339178 0.99135212]
 [1.06841803 0.40497621]
 [0.73412171 0.90077144]
 [0.49952148 0.13386772]
 [0.63548323 0.85424215]
 [0.8000667  1.56262366]
 [0.13730421 0.47155105]
 [0.82570838 1.1368839 ]
 [1.14011933 0.78612406]]


**Q7.Given the vector [1, 2, 3, 4, 5], construct a new vector by inserting three consecutive zeros between each element.**

In [83]:
#7
arr = np.array([1, 2, 3, 4, 5])
q7 = np.zeros(len(arr) + (len(arr) - 1) * 3, dtype=arr.dtype)
q7[::4] = arr
print(q7)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


**Q8. What are the result of the following expressions?First guess a result, then print the result, and finally find why.**

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 
hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2))


In [84]:
#8
print("0 * np.nan:", 0 * np.nan)
print("np.nan == np.nan:", np.nan == np.nan)
print("np.inf > np.nan:", np.inf > np.nan)
print("np.nan - np.nan:", np.nan - np.nan)
print("np.nan in set([np.nan]):", np.nan in set([np.nan]))
print("0.3 == 3 * 0.1:", 0.3 == 3 * 0.1)

0 * np.nan: nan
np.nan == np.nan: False
np.inf > np.nan: False
np.nan - np.nan: nan
np.nan in set([np.nan]): True
0.3 == 3 * 0.1: False


**Q9. What are the result of the following expressions?First guess a result, then print the result, and finally find why.**
(Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)




In [85]:
#9
print("np.array(0) / np.array(0):", np.array(0) / np.array(0))
print("np.array(0) // np.array(0):", np.array(0) // np.array(0))
print("np.array([np.nan]).astype(int).astype(float):", np.array([np.nan]).astype(int).astype(float))

np.array(0) / np.array(0): nan
np.array(0) // np.array(0): 0
np.array([np.nan]).astype(int).astype(float): [0.]


/var/folders/y_/8g0ym9617yz6ss0zzw8x8vc00000gn/T/ipykernel_75462/3834757046.py:2: RuntimeWarning: invalid value encountered in divide
  print("np.array(0) / np.array(0):", np.array(0) / np.array(0))
/var/folders/y_/8g0ym9617yz6ss0zzw8x8vc00000gn/T/ipykernel_75462/3834757046.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print("np.array(0) // np.array(0):", np.array(0) // np.array(0))
/var/folders/y_/8g0ym9617yz6ss0zzw8x8vc00000gn/T/ipykernel_75462/3834757046.py:4: RuntimeWarning: invalid value encountered in cast
  print("np.array([np.nan]).astype(int).astype(float):", np.array([np.nan]).astype(int).astype(float))
